initial state:

$| in \rangle = \otimes_{j=1}^N \dfrac{1}{\sqrt{2}}\begin{pmatrix} i \\ 1 \end{pmatrix}_j$

initial Hamiltonian:

$H_0 = \sum\limits_{j=1}^N \dfrac{\omega_j}{2} \sigma^y_j$

quenched Hamiltonian:

$H = H_0 + g(t)V =\sum\limits_{j=1}^N \dfrac{\omega_j}{2} \sigma^y_j + g(t)\left( \sum\limits_{j_1 > j_2}^N J_{j_1 j_2} c_{j_1}^\dagger c_{j_2} +  h.c. \right)$

$g(t) = \theta(t) - \theta(t-\tau)$

$\overline{|J_{ij}|^2} = J^2/N$

$c_j^\dagger = \sigma^+_j \left( \prod\limits_{l=1}^{j-1}\sigma^z_l\right), \quad c_j = \left( \prod\limits_{l=1}^{j-1}\sigma^z_l \right) \sigma^-_j$

excitations occupation probabilities:

$p_l(t \geq \tau) = p_l(\tau) = |\langle l | \psi(\tau) \rangle|^2 =  |\langle l | \exp(- i H \tau) | in \rangle|^2$

$ |l \rangle = | k i \rangle$ -- eigenstates of $H_0$ in spectral representation, where $k$ is the number of excitations and $i$ accounts for the states with the same $k$

total energy:

$E =  \sum\limits_l \varepsilon_l \, p_l(\tau)$

$\varepsilon_l$ -- many-body energy levels

total energy averaged over realizations:

$\langle E \rangle = \dfrac{1}{n_r} \sum\limits_{\alpha=1}^{n_r} \sum\limits_l \varepsilon_l \, p_l(\tau)$

$\alpha$ -- replica index for a given realization of coupling constants $\lbrace J_{j_1 j_2} \rbrace$

$n_r$ -- number of realizatons

total energy fluctuations:

${\it Var} E = \langle E^2 \rangle - \langle E \rangle^2 = \dfrac{1}{n_r} \sum\limits_{\alpha=1}^{n_r} \sum\limits_l \varepsilon_l^2 \, p^{(\alpha)}_l(\tau) - \left(\dfrac{1}{n_r} \sum\limits_{\alpha=1}^{n_r} \sum\limits_l \varepsilon_l \, p^{(\alpha)}_l(\tau) \right)^2$

# Execute

In [1]:
%run "C:\Users\Nick\Projects\thermalization_sim\v5_resubmission\SYK2_thermalizer.py" 

In [2]:
# the parameters: 
# num -- number of qubits
# num_ex -- number of the initial state. It ranges from 0 to 2^N - 1.
# Jc -- square root of the variance of random couplings J_{ij}
# nr -- number of realizations
# do -- levels' spacing
# t_min -- mininum time
# t_max -- maximum time
# nt -- number of time points

In [3]:
perm_SYK2(4)

[['I', 'I', 'ZM', 'P'],
 ['I', 'ZM', 'Z', 'P'],
 ['I', 'ZM', 'P', 'I'],
 ['ZM', 'Z', 'Z', 'P'],
 ['ZM', 'Z', 'P', 'I'],
 ['ZM', 'P', 'I', 'I']]

In [4]:
perm_diag(4)

[['I', 'I', 'I', 'Y'],
 ['I', 'I', 'Y', 'I'],
 ['I', 'Y', 'I', 'I'],
 ['Y', 'I', 'I', 'I']]

In [12]:
num = 4 
nr = 100 
Jc = 1
#coupling_consts = np.load('data/couplings_N={}_nr={}_J={}.npy'.format(num, nr, Jc), allow_pickle = True)
coupling_consts_QC = np.load('data/couplings_QC_N={}_nr={}_J={}.npy'.format(num, nr, Jc), allow_pickle = True)

In [13]:
coupling_consts_QC.shape

(100, 6)

In [15]:
coupling_consts_QC[99]

array([-0.15846948-0.63258899j, -0.48252546-0.18127957j,
        0.52956418+0.236623j  , -0.30600745-0.30806431j,
        0.42812029+0.47108844j,  0.05272563-0.0112204j ])

In [16]:
gen_energ4(num = 4)
# we print the single-particle energies
# we print the many-body energies

[0.28 0.38 0.63 0.86]
[-1.075 -0.795 -0.695 -0.445 -0.415 -0.215 -0.165 -0.065  0.065  0.165
  0.215  0.415  0.445  0.695  0.795  1.075]


In [17]:
sp_levs = np.load('data/sp_levels_N={}.npy'.format(4), allow_pickle = True)
energ = np.load('data/energ_N={}.npy'.format(4),allow_pickle = True)

In [18]:
import numpy as np
from numpy.linalg import eig
from numpy.linalg import eigvalsh

In [20]:
n = 4
nr = 100
min_ls = np.zeros(nr)
mb_levels = [] * nr
level_sps = [] * nr
for j in range(nr):
    H_mat =H_0(n, sp_levs) #+ H_SYK2(n, coupling_consts_QC[j])
    for i1 in range(2 ** n):
            for i2 in range(2 ** n):
                if H_mat[i1][i2] - np.conjugate(H_mat[i2][i1]) != 0.:
                    print('Hermicity check fails!') 
    evs = np.sort(eigvalsh(H_mat))
    mb_levels.append(evs)
    ls_list = []
    for k in range(int(len(evs))-1):
        ls_list.append(np.abs(evs[k]-evs[k+1]))       
    min_ls[j] = min(ls_list)
    level_sps.append(np.array(ls_list))
    
#level_sps_av = np.sum(np.array(level_sps),0)/nr   
#min(level_sps_av)
np.sum(min_ls)/nr   

np.float64(0.03000000000000009)

In [21]:
n = 4
nr = 100
min_ls = np.zeros(nr)
mb_levels = [] * nr
level_sps = [] * nr
for j in range(nr):
    H_mat =H_0(n, sp_levs) + H_SYK2(n, coupling_consts_QC[j])
    for i1 in range(2 ** n):
            for i2 in range(2 ** n):
                if H_mat[i1][i2] - np.conjugate(H_mat[i2][i1]) != 0.:
                    print('Hermicity check fails!') 
    evs = np.sort(eigvalsh(H_mat))
    mb_levels.append(evs)
    ls_list = []
    for k in range(int(len(evs))-1):
        ls_list.append(np.abs(evs[k]-evs[k+1]))       
    min_ls[j] = min(ls_list)
    level_sps.append(np.array(ls_list))
    
#level_sps_av = np.sum(np.array(level_sps),0)/nr   
#min(level_sps_av)
np.sum(min_ls)/nr   

np.float64(0.07357960795622477)

In [23]:
n = 4
nr = 100
#min_ls = np.zeros(nr)
mb_levels = [] * nr
#level_sps = [] * nr
for j in range(nr):
    H_mat =H_0(n, sp_levs) + H_SYK2(n, coupling_consts_QC[j])
    for i1 in range(2 ** n):
            for i2 in range(2 ** n):
                if H_mat[i1][i2] - np.conjugate(H_mat[i2][i1]) != 0.:
                    print('Hermicity check fails!') 
    evs = np.sort(eigvalsh(H_mat))
    mb_levels.append(evs)

mb_levels_av = np.sum(np.array(mb_levels),0)/nr    

ls_list = []
for k in range(int(len(mb_levels_av))-1):
    ls_list.append(np.abs(mb_levels_av[k]-mb_levels_av[k+1]))       
#min_ls[j] = min(ls_list)

min(ls_list)
    
#    ls_list = []
#    for k in range(int(len(evs))-1):
#        ls_list.append(np.abs(evs[k]-evs[k+1]))       
#    #min_ls[j] = min(ls_list)
#    level_sps.append(np.array(ls_list))
    
#level_sps_av = np.sum(np.array(level_sps),0)/nr   
#min(level_sps_av)
#np.sum(min_ls)/nr  

np.float64(0.15815759636373422)

In [24]:
mb_levels_av

array([-1.85668713, -1.45228979, -1.15215976, -0.8739526 , -0.66180273,
       -0.46435224, -0.25339082, -0.07265727,  0.08550033,  0.26176383,
        0.45655818,  0.64584938,  0.87345771,  1.15971166,  1.45660212,
        1.84784914])

In [26]:
np.sum(mb_levels[0])

np.float64(4.440892098500626e-16)

In [27]:
level_sps_av = np.sum(np.array(level_sps),0)/nr

In [28]:
mb_levels_av = np.sum(np.array(mb_levels),0)/nr

In [29]:
mb_levels[0]

array([-1.71090478, -1.39235365, -1.10864682, -0.93981299, -0.60526977,
       -0.3057785 , -0.18294556, -0.12107547,  0.05375893,  0.17524237,
        0.4815572 ,  0.60196424,  0.86113148,  1.16795012,  1.35099883,
        1.67418436])

In [47]:
SYK2(num = 4, num_ex = 0, Jc = 1, nr = 100, t_min = 0, t_max = 20, nt = 401)
# we print the initial energy and the number of the evaluated realization

-1.7977317199999963
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [4]:
entropy(num = 4, Jc = 1, nr = 100, t_min = 0, t_max = 20, nt = 401)

-1.0749999999999993
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
-0.21499999999999989
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
-0.44499999999999973
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
-0.6949999999999994
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
1

In [11]:
SYK2_long(num = 4, num_ex = 15, Jc = 1, nr = 100, t_min = 0, t_max = 160, nt = 401)
# we print the initial energy and the number of the evaluated realization

1.0749999999999993
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
